### ISSUE TITLE
Dar personalidade ao bot

### ISSUE THREAD

**Issue by clarissalimab** [Hargre/faltometro-bot#1]
### Novas respostas conforme o usuário adiciona novas faltas:
- [x] Adiciona a primeira falta em uma disciplina
  1. "Poxa... Você estava indo tão bem"
  2. "Pra tudo tem a primeira vez, né?"
  3. "E eu que achava que você era um bom exemplo de aluno."
- [x] Adiciona a segunda falta em uma disciplina
  1. "Tá virando um hábito, hein?"
  2. "Putz, agora que tudo desanda"
  3. "De novo???"
- [x] Ultrapassa metade das faltas permitidas
  1. "Você sabe que não é uma competição, né?"
  2. "Você ainda lembra onde é a sua sala?"
  3. "Você ta ciente do que você ta fazendo?"
- [x] Chega ao limite de faltas
  1. "O professor sabe que você tá fazendo essa matéria?"
  2. "Espero que você não fique doente a partir de agora"
  3. "Sem emoção não tem graça, né?"
- [x] Ultrapassa o limite de faltas
  1. "MANO DO CÉU espero que seu professor não ligue pra faltas"
  2. "Você ri da cara do perigo, tô impressionado."
  3. "O que mais me espanta é você ainda ter coragem de vir aqui me mandar isso."
- [x] Em qualquer situação
  1. "Aposto que essa aula era importante só porque você faltou kkkk"
  2. "Fiquei sabendo que hoje tinha prova surpresa"
  3. "Espero que você tenha uma boa explicação pra isso."

**Comment by clarissalimab** [comment]
@Hargre adicionei as falas nos tópicos rs

**Comment by Hargre** [comment]
@clarissalimab confere aí
